In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("vgsales_10.csv")
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,14941,Stake: Fortune Fighters,XB,2003.0,Fighting,Metro 3D,0.02,0.01,0.00,0.00,0.02
1,9817,Street Hoops,GC,NaN,Sports,Unknown,0.09,0.02,0.00,0.00,0.12
2,9224,Wild ARMs XF,PSP,2007.0,Role-Playing,505 Games,0.07,0.00,0.06,0.01,0.14
3,15756,Memories Off: Yubikiri no Kikou,PSP,2011.0,Adventure,5pb,0.00,0.00,0.02,0.00,0.02
4,1398,Hannah Montana: Spotlight World Tour,Wii,2007.0,Action,Disney Interactive Studios,0.87,0.38,0.00,0.13,1.39
...,...,...,...,...,...,...,...,...,...,...,...
548,14766,Infinite Stratos 2: Ignition Hearts,PS3,2014.0,Adventure,5pb,0.00,0.00,0.03,0.00,0.03
549,9554,Backyard Baseball,GC,2003.0,Sports,Infogrames,0.10,0.03,0.00,0.00,0.13
550,2693,Driv3r,XB,2004.0,Racing,Atari,0.36,0.38,0.00,0.03,0.76
551,6026,Top Gear Overdrive,N64,1998.0,Racing,Kemco,0.23,0.06,0.00,0.00,0.29
552,10313,Langrisser IV,SAT,1997.0,Strategy,NCS,0.00,0.00,0.11,0.00,0.11

In [4]:
from sklearn.preprocessing import OrdinalEncoder
Oenc = OrdinalEncoder()
Oenc.fit(df[['Platform','Genre','Publisher']])
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,14941,Stake: Fortune Fighters,XB,2003.0,Fighting,Metro 3D,0.02,0.01,0.00,0.00,0.02
1,9817,Street Hoops,GC,NaN,Sports,Unknown,0.09,0.02,0.00,0.00,0.12
2,9224,Wild ARMs XF,PSP,2007.0,Role-Playing,505 Games,0.07,0.00,0.06,0.01,0.14
3,15756,Memories Off: Yubikiri no Kikou,PSP,2011.0,Adventure,5pb,0.00,0.00,0.02,0.00,0.02
4,1398,Hannah Montana: Spotlight World Tour,Wii,2007.0,Action,Disney Interactive Studios,0.87,0.38,0.00,0.13,1.39
...,...,...,...,...,...,...,...,...,...,...,...
548,14766,Infinite Stratos 2: Ignition Hearts,PS3,2014.0,Adventure,5pb,0.00,0.00,0.03,0.00,0.03
549,9554,Backyard Baseball,GC,2003.0,Sports,Infogrames,0.10,0.03,0.00,0.00,0.13
550,2693,Driv3r,XB,2004.0,Racing,Atari,0.36,0.38,0.00,0.03,0.76
551,6026,Top Gear Overdrive,N64,1998.0,Racing,Kemco,0.23,0.06,0.00,0.00,0.29
552,10313,Langrisser IV,SAT,1997.0,Strategy,NCS,0.00,0.00,0.11,0.00,0.11

In [15]:
Oenc.categories_

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24], dtype=int64),
 array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
         11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
         22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
         33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
         44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
         55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
         66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
         77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
         88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
         99., 100., 101., 102., 103., 104., 105., 106., 107., 108., 109.,
        110., 111., 112., 113., 114., 115., 116., 117., 118., 119., 120.,
        121., 122., 123., 124., 125., 126., 127., 128., 129.,  nan])]

In [5]:
from sklearn.preprocessing import LabelEncoder
Lenc = LabelEncoder()
Lenc.fit(df['Genre'])
df['Genre'] = Lenc.fit_transform(df['Genre'])
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,14941,Stake: Fortune Fighters,XB,2003.0,2,Metro 3D,0.02,0.01,0.00,0.00,0.02
1,9817,Street Hoops,GC,NaN,10,Unknown,0.09,0.02,0.00,0.00,0.12
2,9224,Wild ARMs XF,PSP,2007.0,7,505 Games,0.07,0.00,0.06,0.01,0.14
3,15756,Memories Off: Yubikiri no Kikou,PSP,2011.0,1,5pb,0.00,0.00,0.02,0.00,0.02
4,1398,Hannah Montana: Spotlight World Tour,Wii,2007.0,0,Disney Interactive Studios,0.87,0.38,0.00,0.13,1.39
...,...,...,...,...,...,...,...,...,...,...,...
548,14766,Infinite Stratos 2: Ignition Hearts,PS3,2014.0,1,5pb,0.00,0.00,0.03,0.00,0.03
549,9554,Backyard Baseball,GC,2003.0,10,Infogrames,0.10,0.03,0.00,0.00,0.13
550,2693,Driv3r,XB,2004.0,6,Atari,0.36,0.38,0.00,0.03,0.76
551,6026,Top Gear Overdrive,N64,1998.0,6,Kemco,0.23,0.06,0.00,0.00,0.29
552,10313,Langrisser IV,SAT,1997.0,11,NCS,0.00,0.00,0.11,0.00,0.11

In [6]:
Lenc.classes_

array(['Action', 'Adventure', 'Fighting', 'Misc', 'Platform', 'Puzzle',
       'Racing', 'Role-Playing', 'Shooter', 'Simulation', 'Sports',
       'Strategy'], dtype=object)

In [7]:
from sklearn.preprocessing import OneHotEncoder
Onhot = OneHotEncoder()
Onhot.fit(df[['Platform']])
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,14941,Stake: Fortune Fighters,XB,2003.0,2,Metro 3D,0.02,0.01,0.00,0.00,0.02
1,9817,Street Hoops,GC,NaN,10,Unknown,0.09,0.02,0.00,0.00,0.12
2,9224,Wild ARMs XF,PSP,2007.0,7,505 Games,0.07,0.00,0.06,0.01,0.14
3,15756,Memories Off: Yubikiri no Kikou,PSP,2011.0,1,5pb,0.00,0.00,0.02,0.00,0.02
4,1398,Hannah Montana: Spotlight World Tour,Wii,2007.0,0,Disney Interactive Studios,0.87,0.38,0.00,0.13,1.39
...,...,...,...,...,...,...,...,...,...,...,...
548,14766,Infinite Stratos 2: Ignition Hearts,PS3,2014.0,1,5pb,0.00,0.00,0.03,0.00,0.03
549,9554,Backyard Baseball,GC,2003.0,10,Infogrames,0.10,0.03,0.00,0.00,0.13
550,2693,Driv3r,XB,2004.0,6,Atari,0.36,0.38,0.00,0.03,0.76
551,6026,Top Gear Overdrive,N64,1998.0,6,Kemco,0.23,0.06,0.00,0.00,0.29
552,10313,Langrisser IV,SAT,1997.0,11,NCS,0.00,0.00,0.11,0.00,0.11

In [23]:
Onhot.categories_

[array(['2600', '3DS', 'DC', 'DS', 'GB', 'GBA', 'GC', 'GEN', 'N64', 'NES',
        'PC', 'PS', 'PS2', 'PS3', 'PS4', 'PSP', 'PSV', 'SAT', 'SNES',
        'TG16', 'Wii', 'WiiU', 'X360', 'XB', 'XOne'], dtype=object)]

In [10]:
Onhot.transform(df[['Platform']]).toarray()

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [14]:
from sklearn.preprocessing import Normalizer
Norm = Normalizer()
df[['NA_Sales','EU_Sales','JP_Sales','Other_Sales','Global_Sales']] = Norm.fit_transform(df[['NA_Sales','EU_Sales','JP_Sales','Other_Sales','Global_Sales']])
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,14941,Stake: Fortune Fighters,XB,2003.0,2,Metro 3D,0.019995,0.009998,0.000000,0.000000,0.999750
1,9817,Street Hoops,GC,NaN,10,Unknown,0.089620,0.019916,0.000000,0.000000,0.995777
2,9224,Wild ARMs XF,PSP,2007.0,7,505 Games,0.069701,0.000000,0.059744,0.009957,0.995728
3,15756,Memories Off: Yubikiri no Kikou,PSP,2011.0,1,5pb,0.000000,0.000000,0.019996,0.000000,0.999800
4,1398,Hannah Montana: Spotlight World Tour,Wii,2007.0,0,Disney Interactive Studios,0.628163,0.274370,0.000000,0.093863,0.722026
...,...,...,...,...,...,...,...,...,...,...,...
548,14766,Infinite Stratos 2: Ignition Hearts,PS3,2014.0,1,5pb,0.000000,0.000000,0.029987,0.000000,0.999550
549,9554,Backyard Baseball,GC,2003.0,10,Infogrames,0.099459,0.029838,0.000000,0.000000,0.994594
550,2693,Driv3r,XB,2004.0,6,Atari,0.318834,0.336547,0.000000,0.026569,0.885650
551,6026,Top Gear Overdrive,N64,1998.0,6,Kemco,0.223765,0.058374,0.000000,0.000000,0.972893
552,10313,Langrisser IV,SAT,1997.0,11,NCS,0.000000,0.000000,0.109340,0.000000,0.994004

In [17]:
from sklearn.model_selection import train_test_split
Y = df['Platform']
X = df.drop(columns=['Platform'])
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [18]:
x_train

,Rank,Name,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
18,14325,Smart Girl's Winter Wonderland,2008.0,3,UFO Interactive,0.029987,0.000000,0.000000,0.000000,0.999550
325,11599,FabStyle,2011.0,11,Tecmo Koei,0.000000,0.000000,0.079745,0.000000,0.996815
486,8692,Infected,2005.0,8,THQ,0.138641,0.000000,0.000000,0.009903,0.990293
296,4072,Asphalt 3D,2011.0,6,Ubisoft,0.257376,0.152519,0.019065,0.038130,0.953246
478,9139,Eternal Poison,2008.0,7,Banpresto,0.069729,0.049806,0.000000,0.019922,0.996123
...,...,...,...,...,...,...,...,...,...,...
71,10497,Revolution X,1995.0,8,Acclaim Entertainment,0.059842,0.039894,0.000000,0.009974,0.997360
106,13839,Tokimeki Mahjong Paradise: Koi no Tenpai Beat,1995.0,3,Sonnet,0.000000,0.000000,0.039968,0.000000,0.999201
270,13197,Classic Dungeon X2,2011.0,7,Nippon Ichi Software,0.000000,0.000000,0.049938,0.000000,0.998752
435,3473,Tales of Phantasia,1998.0,7,Namco Bandai Games,0.000000,0.000000,0.474855,0.035174,0.879361
102,779,Borderlands,2009.0,8,Take-Two Interactive,0.703634,0.363544,0.000000,0.170045,0.586362

In [19]:
x_test

,Rank,Name,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
548,14766,Infinite Stratos 2: Ignition Hearts,2014.0,1,5pb,0.000000,0.000000,0.029987,0.000000,0.999550
82,13430,Tropico 3,2009.0,11,Kalypso Media,0.000000,0.039966,0.000000,0.009992,0.999151
523,9645,Quantum Redshift,2002.0,6,Microsoft Game Studios,0.089598,0.029866,0.000000,0.000000,0.995530
332,15999,Captain Morgane and the Golden Turtle,2012.0,1,Reef Entertainment,0.000000,0.010000,0.000000,0.000000,0.999950
132,10715,Rio,2011.0,3,THQ,0.049913,0.029948,0.000000,0.009983,0.998255
...,...,...,...,...,...,...,...,...,...,...
140,16171,Wallace & Gromit: Curse of the Were-Rabbit,2005.0,1,Konami Digital Entertainment,0.010000,0.000000,0.000000,0.000000,0.999950
149,8284,Sound Novel Evolution 1: Otogirisou Sosei-Hen,1999.0,1,ChunSoft,0.000000,0.000000,0.157983,0.009874,0.987392
498,12938,Dengeki Gakuen RPG: Cross of Venus,2009.0,7,ASCII Media Works,0.000000,0.000000,0.049938,0.000000,0.998752
153,4362,World Soccer Winning Eleven 5 Final Evolution,2001.0,10,Konami Digital Entertainment,0.000000,0.000000,0.410365,0.000000,0.911922
172,5603,Overlord II,2009.0,0,Codemasters,0.107957,0.147215,0.000000,0.058886,0.981430

In [20]:
y_train

18      DS
325     DS
486    PSP
296    3DS
478    PS2
      ...
71      PS
106    SAT
270    PSP
435     PS
102    PS3
Name: Platform, Length: 442, dtype: object

In [21]:
y_test

548     PS3
82       PC
523      XB
332     Wii
132    X360
       ...
140      XB
149      PS
498      DS
153     PS2
172     PS3
Name: Platform, Length: 111, dtype: object

In [22]:
print('Кол-во входных обучающих данных',len(x_train))
print('Кол-во входных проверенных обучающих данных',len(y_train))
print('Кол-во входных тестовых данных',len(x_test))
print('Кол-во входных проверенных тестовых данных',len(y_test))

Кол-во входных обучающих данных 442
Кол-во входных проверенных обучающих данных 442
Кол-во входных тестовых данных 111
Кол-во входных проверенных тестовых данных 111